//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWM_3D_Integration.Src.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TWM_3D_Integration.Src.Resource.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT NumInSale FROM OITM WHERE ItemCode = &apos;{0}&apos;.
        /// </summary>
        internal static string B2B_GET_ITEM_NUM_IN_SALES {
            get {
                return ResourceManager.GetString("B2B_GET_ITEM_NUM_IN_SALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @AlertName NVARCHAR(50) = &apos;B2B Process Alert&apos;
        ///SELECT T0.DocNum B2BEntry, Case T0.U_TWM_DRCT WHEN &apos;E&apos; THEN &apos;Export&apos; WHEN &apos;I&apos; Then &apos;Import&apos; ELSE &apos;&apos; END Direction , CASE T1.U_TWM_OBTP WHEN &apos;1250000001&apos; THEN &apos;Inv. Trans Request&apos; 
        ///							WHEN &apos;17&apos; THEN &apos;Sales Order&apos;
        ///							WHEN &apos;67&apos; THEN &apos;Inv. Trans&apos; 
        ///							WHEN &apos;13&apos; THEN &apos;AR Invoice&apos;
        ///							WHEN &apos;59&apos; THEN &apos;Goods Receipt&apos;
        ///							WHEN &apos;60&apos; THEN &apos;Goods Issue&apos;
        ///							WHEN &apos;112&apos; THEN CASE T0.U_TWM_OBTP WHEN &apos;IRT&apos; THEN &apos;Draft Goods Receipt&apos; ELSE &apos;Draf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string B2B_PROCESS_ALERT {
            get {
                return ResourceManager.GetString("B2B_PROCESS_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONVERT(INT,ROW_NUMBER() OVER (ORDER BY T0.DocEntry)) ID, &apos;Y&apos; Slct, &apos;&apos; [TYPE], T0.ObjType [OBTP], T0.DocEntry [DCEN], T0.DocNum [DCNM], T0.NumAtCard [POREF]
        ///	, T0.DocTotal [DCTTL]
        ///	, CONVERT(INT,NULL) B2BL, CONVERT(NVARCHAR(254),&apos;&apos;) FLNM, CONVERT(NVARCHAR(254),&apos;&apos;) RMRK
        ///FROM OINV T0
        ///WHERE DocEntry &lt;&gt; DocEntry.
        /// </summary>
        internal static string B2BEXPORT_EMPTY_RECORDS {
            get {
                return ResourceManager.GetString("B2BEXPORT_EMPTY_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DFI_INV_DETAIL_DETAIL
        ///DECLARE @Entry int = {0}
        ///IF OBJECT_ID(&apos;TEMPDB..#DETAIL&apos;) IS NOT NULL BEGIN DROP TABLE #DETAIL END
        ///
        ///CREATE TABLE #DETAIL (
        ///	DetailTag NCHAR(3)
        ///	, VendorCode NCHAR(5)
        ///	, StoreCode NCHAR(6)
        ///	, DSPNumber NCHAR(10)
        ///	, PONumber NCHAR(10)
        ///	, InvoiceNumber NCHAR(15)
        ///	, SerialNumber NCHAR(6)		--Running Number by Invoice	(LineNum)
        ///	, ItemCode NCHAR(14)			--Supplier Item Code
        ///	, InvoiceQty NCHAR(10)		--Up to 2 decimal places - Max of 9999999.99 - Including decimal point.		-Right Al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DFI_INV_DETAIL_DETAIL {
            get {
                return ResourceManager.GetString("DFI_INV_DETAIL_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DFI_INV_DETAIL_HEADER
        ///DECLARE @Entry INT = {0}
        ///IF OBJECT_ID(&apos;TEMPDB..#HEADER&apos;) IS NOT NULL BEGIN DROP TABLE #HEADER END
        ///
        ///CREATE TABLE #HEADER (
        ///	HeaderTag NCHAR(3)
        ///	, VendorCode NCHAR(5)
        ///	, StoreCode NCHAR(6)
        ///	, DSPNumber NCHAR(10)
        ///	, PONumber NCHAR(10)
        ///	, PODate NCHAR(8)			--yyyyMMdd
        ///	, DeliveryDate NCHAR(8)		--yyyyMMdd
        ///	, InvoiceNumber NCHAR(15)
        ///	, InvoiceDate NCHAR(8)		--yyyyMMdd
        ///	, GSTValue NCHAR(13)			--2decimal places - Max of 999999.99 - Include decimal point. - Prefix with 2 spaces		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DFI_INV_DETAIL_HEADER {
            get {
                return ResourceManager.GetString("DFI_INV_DETAIL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DFI_INV_SUMMARY
        ///DECLARE @Entry int = {0}
        ///
        ///IF OBJECT_ID(&apos;TEMPDB..#SUMMARY&apos;) IS NOT NULL BEGIN DROP TABLE #SUMMARY END
        ///
        ///CREATE TABLE #SUMMARY (
        ///	VendorCode CHAR(5)
        ///	, TransactionDate CHAR(8)
        ///	, InvoiceCount CHAR(5)
        ///	, TotalLines CHAR(8)
        ///	, TotalValue CHAR(15)
        ///	, FullCompanyName CHAR(40)
        ///	, VendorAddress1 CHAR(35)
        ///	, VendorAddress2 CHAR(35)
        ///	, VendorAddress3 CHAR(35)
        ///	, VendorAddress4 CHAR(35)
        ///	, Country CHAR(9)
        ///	, PostalCode CHAR(10)
        ///	, CompanyReg CHAR(30)
        ///	, GSTReg CHAR(15)
        ///	, InvoiceTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DFI_INV_SUMMARY {
            get {
                return ResourceManager.GetString("DFI_INV_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONVERT(INT,ROW_NUMBER() OVER (ORDER BY T0.DocEntry)) ID, &apos;Y&apos; Slct, &apos;DFI_INV&apos; [TYPE], T0.ObjType [OBTP], T0.DocEntry [DCEN], T0.DocNum [DCNM], T0.NumAtCard [POREF]
        ///	, T0.DocTotal [DCTTL]
        ///	, CONVERT(INT,NULL) B2BL, CONVERT(NVARCHAR(254),&apos;&apos;) FLNM, CONVERT(NVARCHAR(254),&apos;&apos;) RMRK
        ///FROM OINV T0 WITH(NOLOCK) JOIN INV1 T1 WITH(NOLOCK) ON T0.DocEntry = T1.DocEntry
        ///	LEFT JOIN (SELECT C1.U_TWM_ENTR, C1.U_TWM_LNUM FROM [@TWM_OB2BL] C0 WITH(NOLOCK) JOIN [@TWM_B2BL1] C1 WITH(NOLOCK) ON C0.DocEntry = C1.DocEntr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_DFI_INV_RECORDS {
            get {
                return ResourceManager.GetString("GET_DFI_INV_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONVERT(INT,ROW_NUMBER() OVER (ORDER BY T0.DocEntry)) ID, &apos;Y&apos; Slct, &apos;NTUC_CH_INV&apos; [TYPE], T0.ObjType [OBTP], T0.DocEntry [DCEN], T0.DocNum [DCNM], T0.NumAtCard [POREF]
        ///	, T0.DocTotal [DCTTL]
        ///	, CONVERT(INT,NULL) B2BL, CONVERT(NVARCHAR(254),&apos;&apos;) FLNM, CONVERT(NVARCHAR(254),&apos;&apos;) RMRK
        ///FROM OINV T0 WITH(NOLOCK) JOIN INV1 T1 WITH(NOLOCK) ON T0.DocEntry = T1.DocEntry
        ///	LEFT JOIN (SELECT C1.U_TWM_ENTR, C1.U_TWM_LNUM FROM [@TWM_OB2BL] C0  WITH(NOLOCK) JOIN [@TWM_B2BL1] C1  WITH(NOLOCK) ON C0.DocEntry = C1.D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_NTUC_CH_INV_RECORDS {
            get {
                return ResourceManager.GetString("GET_NTUC_CH_INV_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONVERT(INT,ROW_NUMBER() OVER (ORDER BY T0.DocEntry)) ID, &apos;Y&apos; Slct, &apos;NTUC_INV&apos; [TYPE], T0.ObjType [OBTP], T0.DocEntry [DCEN], T0.DocNum [DCNM], T0.NumAtCard [POREF]
        ///	, T0.DocTotal [DCTTL]
        ///	, CONVERT(INT,NULL) B2BL, CONVERT(NVARCHAR(254),&apos;&apos;) FLNM, CONVERT(NVARCHAR(254),&apos;&apos;) RMRK
        ///FROM OINV T0 WITH(NOLOCK) JOIN INV1 T1 WITH(NOLOCK) ON T0.DocEntry = T1.DocEntry
        ///	LEFT JOIN (SELECT C1.U_TWM_ENTR, C1.U_TWM_LNUM FROM [@TWM_OB2BL] C0 WITH(NOLOCK) JOIN [@TWM_B2BL1] C1 WITH(NOLOCK) ON C0.DocEntry = C1.DocEnt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GET_NTUC_INV_RECORDS {
            get {
                return ResourceManager.GetString("GET_NTUC_INV_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;HDR&apos; recordType
        ///	, T0.DocNum invNo
        ///	, CASE T0.CANCELED WHEN &apos;Y&apos; THEN &apos;D&apos; ELSE &apos;A&apos; END docAction
        ///	, GetDate() actionDate
        ///	, &apos;SOR&apos; invType
        ///	, T0.DocDate invDate
        ///	, T0.NumAtCard poNo
        ///	, (SELECT TOP 1 C0.DocDate FROM ORDR C0 WHERE C0.NumAtCard = T0.NumAtCard) poDate
        ///	, &apos;&apos; deliveryNo
        ///	, ISNULL(T0.U_DELDATE,DATEADD(d,1,T0.DocDate)) deliveryDate
        ///	, (SELECT TOP 1 C1.U_TWM_XCUST FROM [@TWM_OB2BS] C1 WHERE C1.Code = &apos;NTUC_CH&apos;) buyerCode
        ///	, T0.CardName buyerName
        ///	, &apos;&apos; buyerAddr1
        ///	, &apos;&apos; buyerAddr2
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTUC_CH_INV_HEADER {
            get {
                return ResourceManager.GetString("NTUC_CH_INV_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;DET&apos; recordType
        ///	, T0.DocNum invNo
        ///	, T1.LineNum
        ///	, T1.VisOrder + 1 seqNo
        ///	, (SELECT C0.Substitute FROM OSCN C0 WHERE C0.CardCode = T0.CardCode AND C0.ItemCode = T2.ItemCode) buyerItemCode
        ///	, T1.ItemCode supplierItemCode
        ///	, T1.CodeBars barCode
        ///	, T1.Dscription itemDesc
        ///	, &apos;&apos; brand
        ///	, &apos;&apos; colourCode
        ///	, &apos;&apos; colourDesc
        ///	, &apos;&apos; sizeCode
        ///	, &apos;&apos; sizeDesc
        ///	, T1.NumPerMsr packingFactor
        ///	, CASE T1.NumPerMsr WHEN &apos;1&apos; THEN &apos;U&apos; ELSE &apos;P&apos; END invBaseUnit
        ///	, T1.UnitMsr invUom
        ///	, T1.Quantity invQty
        ///	, &apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTUC_INV_DETAIL {
            get {
                return ResourceManager.GetString("NTUC_INV_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;HDR&apos; recordType
        ///	, T0.DocNum invNo
        ///	, CASE T0.CANCELED WHEN &apos;Y&apos; THEN &apos;D&apos; ELSE &apos;A&apos; END docAction
        ///	, GetDate() actionDate
        ///	, &apos;SOR&apos; invType
        ///	, T0.DocDate invDate
        ///	, T0.NumAtCard poNo
        ///	, (SELECT TOP 1 C0.DocDate FROM ORDR C0 WHERE C0.NumAtCard = T0.NumAtCard) poDate
        ///	, &apos;&apos; deliveryNo
        ///	, ISNULL(T0.U_DELDATE, DATEADD(d,1,T0.DocDate)) deliveryDate
        ///	, (SELECT TOP 1 C1.U_TWM_XCUST FROM [@TWM_OB2BS] C1 WHERE C1.Code = &apos;NTUC_FP&apos;) buyerCode
        ///	, T0.CardName buyerName
        ///	, &apos;&apos; buyerAddr1
        ///	, &apos;&apos; buyerAddr2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NTUC_INV_HEADER {
            get {
                return ResourceManager.GetString("NTUC_INV_HEADER", resourceCulture);
            }
        }
    }
}
